version: '2'
services:
  nginx:
    image: nginxvhustle
    ports:
      - "18080:80"
      - "18443:443"
    depends_on:
      - vhustle
    volumes:
      - /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/logs:/var/log/
      - /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/target/frontend:/etc/nginx/html/
  db:
    image: postgres:9.5
    env_file: /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/target/postgres.env
#    volumes:
#      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
  vhustle:
    image: vhustle
    env_file: /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/dev.env
    volumes:
      - /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/logs:/var/log/
    depends_on:
      - db
