version: '2'
services:
  nginx:
    build:
      context: /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/prod-files
      dockerfile: /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/prod-files/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vhustle
    volumes:
      - /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/logs:/var/log/
      - /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/target/frontend:/etc/nginx/html/
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    env_file: /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/target/vhustle.postgres.env
  vhustle:
    image: vhustle
    env_file: /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/dev.env
    volumes:
      - /Users/ilyatimofee/prog/axxonsoft/src/github.com/itimofeev/vhustle/tools/logs:/var/log/
    depends_on:
      - db
